name: Sanity Test

on:
  pull_request:
    branches:
    - release-4.9
jobs:
  build_push:
    if: (github.repository == 'kubevirt/must-gather')
    name: Pull Request Sanity
    runs-on: ubuntu-latest
    steps:
    - name: git pull
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17' # The Go version to download (if necessary) and use.
    - name: check vmConvertor
      run: |-
        cd cmd/vmConvertor
        go test .
        go build .
        ls -l
